spring.application.name=herbalance


spring.datasource.url=jdbc:mysql://localhost:3306/herbalance
spring.datasource.username=root
spring.datasource.password=Sebastiangonzalez1812!

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true


